config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'app_tokens/create'
  get 'app_tokens/destry'
  resources :client_apps do
    member do
      get 'integrations', to: 'integrations#index'
    end
    resources :app_tokens
    resources :client_app_errors
  end
  devise_for :users
  root to: 'static#welcome'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/app_token.rb
# frozen_string_literal: true

class AppToken < ApplicationRecord
  belongs_to :client_app
  before_validation :init_token, on: :create
  has_secure_token

  def init_token
    self.expires_at = Time.current + 1.year
  end

  def regenerate
    return false unless can_regenerate?
    AppToken.create(client_app: client_app)
  end

  def recent_token_count(time_frame)
    token_count = AppToken.where(client_app_id: client_app.id)
      .where("created_at >= ?", time_frame)
      .count
  end

  def can_regenerate?
    token_limit = 10
    recent_token_count(Time.current.utc - 5.days) < token_limit
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client_app.rb
# frozen_string_literal: true

class ClientApp < ApplicationRecord
  belongs_to :user
  has_many :client_app_errors
  has_many :app_tokens
  validates_presence_of :name
end

app/models/client_app_error.rb
# frozen_string_literal: true

class ClientAppError < ApplicationRecord
  include ActionView::Helpers::DateHelper
  belongs_to :client_app

  after_create :notify_parties

  scope :recent, -> { where('created_at >= ? ', Time.current.utc - 5.days).order('created_at desc') }

  validates_presence_of :message, :exception_name

  def to_s(timezone = 'America/Chicago')
    "#{exception_name} triggered #{time_ago_in_words(created_at.in_time_zone(timezone))} ago"
  end

  def notify_parties
    webhook_url = 'https://hooks.slack.com/services/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'
    SlackNotifier.new.tap do |slack|
      slack.notify to_s, webhook_url
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :client_apps
end

app/controllers/app_tokens_controller.rb
# frozen_string_literal: true

class AppTokensController < ApplicationController
  before_action :find_client_app

  def destroy
    @new_app_token = AppToken.find(params[:id]).regenerate
    if @new_app_token
      flash[:notice] = 'Generated a new token'
    else
      flash[:alert] = 'Could not regenerate token'
    end
    redirect_to edit_client_app_path(@client_app)
  end

  def create
    @app_token = @client_app.app_tokens.create
    flash[:notice] = 'Generated a new token' if @app_token.persisted?
    redirect_to edit_client_app_path(@client_app)
  end

  protected

  def find_client_app
    @client_app = ClientApp.find(params[:client_app_id])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :debug_request

  def debug_request
    Rails.logger.info request.base_url
    Rails.logger.info request.headers['origin']
  end
end

app/controllers/client_app_errors_controller.rb
# frozen_string_literal: true

class ClientAppErrorsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :find_client_app
  def create
    @client_app_error = @client_app.client_app_errors.build(client_app_error_params)
    if @client_app_error.save
      render json: @client_app_error, status: :created
    else
      render json: @client_app_error.errors, status: :unprocessable_entity
    end
  end

  def client_app_error_params
    params.require(:client_app_error).permit(:exception_name, :backtrace, :message)
  end

  protected

  def find_client_app
    @client_app = ClientApp.find(params[:client_app_id])
  end
end

app/controllers/client_apps_controller.rb
# frozen_string_literal: true

class ClientAppsController < ApplicationController
  before_action :set_client_app, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /client_apps
  # GET /client_apps.json
  def index
    @client_apps = ClientApp.all
  end

  # GET /client_apps/1
  # GET /client_apps/1.json
  def show
    @recent_errors = @client_app.client_app_errors.recent
  end

  # GET /client_apps/new
  def new
    @client_app = ClientApp.new(user: current_user)
  end

  # GET /client_apps/1/edit
  def edit; end

  # POST /client_apps
  # POST /client_apps.json
  def create
    @client_app = ClientApp.new(client_app_params)

    respond_to do |format|
      if @client_app.save
        format.html { redirect_to @client_app, notice: 'Client app was successfully created.' }
        format.json { render :show, status: :created, location: @client_app }
      else
        format.html { render :new }
        format.json { render json: @client_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /client_apps/1
  # PATCH/PUT /client_apps/1.json
  def update
    respond_to do |format|
      if @client_app.update(client_app_params)
        format.html { redirect_to @client_app, notice: 'Client app was successfully updated.' }
        format.json { render :show, status: :ok, location: @client_app }
      else
        format.html { render :edit }
        format.json { render json: @client_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /client_apps/1
  # DELETE /client_apps/1.json
  def destroy
    @client_app.destroy
    respond_to do |format|
      format.html { redirect_to client_apps_url, notice: 'Client app was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_client_app
    @client_app = ClientApp.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def client_app_params
    params.require(:client_app).permit(:user_id, :name)
  end
end

app/controllers/integrations_controller.rb
# frozen_string_literal: true

class IntegrationsController < ApplicationController
  before_action :find_client_app
  def index
    @app_token = @client_app.app_tokens.last
  end

  protected

  def find_client_app
    @client_app = ClientApp.includes(:app_tokens).find(params[:id])
  end
end

app/controllers/static_controller.rb
# frozen_string_literal: true

class StaticController < ApplicationController
  before_action :authenticate_user!
  def welcome
    if(user_signed_in?)
      redirect_to client_apps_path
    end
  end
end

app/helpers/app_tokens_helper.rb
# frozen_string_literal: true

module AppTokensHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/client_app_errors_helper.rb
# frozen_string_literal: true

module ClientAppErrorsHelper
end

app/helpers/client_apps_helper.rb
# frozen_string_literal: true

module ClientAppsHelper
end

app/helpers/integrations_helper.rb
# frozen_string_literal: true

module IntegrationsHelper
end

app/helpers/static_helper.rb
# frozen_string_literal: true

module StaticHelper
end

app/views/app_tokens/create.html.erb
<h1>AppTokens#create</h1>
<p>Find me in app/views/app_tokens/create.html.erb</p>

app/views/app_tokens/destry.html.erb
<h1>AppTokens#destry</h1>
<p>Find me in app/views/app_tokens/destry.html.erb</p>

app/views/client_app_errors/create.html.erb
<h1>ClientAppErrors#create</h1>
<p>Find me in app/views/client_app_errors/create.html.erb</p>

app/views/client_apps/_form.html.erb
<%= form_with(model: client_app, local: true) do |form| %>
  <% if client_app.errors.any? %>
    <div class='row'>
      <div id="col s12">
        <ul>
        <% client_app.errors.full_messages.each do |message| %>
          <li class='red-text'><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id %>

  <div class='row'>
    <div class='input-field col s12'>
      <%= form.text_field :name, class: 'validate' %>
      <%= form.label :name %>
      <span class="helper-text" data-error="wrong">* Required</span>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn' %>
  </div>
<% end %>

app/views/client_apps/_profile.html.erb
<% breadcrumbs ||= [] %>
<% breadcrumbs.unshift({url: client_app_path(@client_app), text: @client_app.name}) %>
<div class='container'>
  <div class="row">
    <div class='s12'>
      <nav>
        <div class="nav-wrapper">
          <div class="col s12">
            <%= link_to "Apps", client_apps_path, class: 'breadcrumb' %>
            <% breadcrumbs.each do |breadcrumb| %>
              <%= link_to breadcrumb[:text], breadcrumb[:url], class: 'breadcrumb' %>
            <% end %>
          </div>
        </div>
      </nav>
    </div>
  </div>


  <div class="row">

    <div id='client-app-profile-nav' class="col s12 m4 l3"> <!-- Note that "m4 l3" was added -->
      <ul>
        <li><%= link_to "Dashboard", @client_app %></li>
        <li><%= link_to "Error History", '#' %></li>
      </ul>
      <hr/>
      <ul>
        <li><%= link_to 'Integrations', integrations_client_app_path(@client_app) %></li>
        <li><%= link_to "Modify App", edit_client_app_path(@client_app) %></li>
      </ul>
    </div>
    <div id='client-app-profile-section' class="col s12 m8 l9"> <!-- Note that "m4 l3" was added -->
      <%= yield %>
    </div>
  </div>
</div>

app/views/client_apps/edit.html.erb
<%= render 'client_apps/profile' do %>
  <div class="row">
    <div class="col s12">
      <h5>Edit Details</h5>
      <%= render 'form', client_app: @client_app %>
    </div>
    <div class="col s12">
      <h5>App Token</h5>
      <% app_token = @client_app.app_tokens.last %>
      <% if app_token %>
        <div>
          <pre><%= app_token.token %></pre>
        </div>
        <div>
          <%= link_to 'Refresh', client_app_app_token_path(@client_app, app_token), method: :delete, class: "btn #{app_token.can_regenerate? ? '' : 'disabled'}" %>
        </div>
      <% else %>
        <%= link_to 'Generate Token', client_app_app_tokens_path(@client_app), method: :post, class: 'btn' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/client_apps/index.html.erb
<div class='container'>
  <div class="row">
    <div id='' class="col s12 m4 l3"> <!-- Note that "m4 l3" was added -->
      <ul>
        <li>
          <%= link_to 'New Client App', new_client_app_path, class: '' %>
        </li>
        <li>
          <%= link_to 'My Account', new_client_app_path, class: '' %>
        </li>
      </ul>
    </div>
    <div id='' class="col s12 m8 l9"> <!-- Note that "m4 l3" was added -->
      <table class='striped'>
        <thead>
          <tr>
            <th>Name</th>
            <th colspan="3">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @client_apps.each do |client_app| %>
            <tr>
              <td><%= client_app.name %></td>
              <td><%= link_to 'Show', client_app %></td>
              <td><%= link_to 'Destroy', client_app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/client_apps/new.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 m6 offset-m3">
      <div class="card">
        <div class="card-content">
          <span class="card-title">New App</span>
        </div>
        <div class="card-action">
          <%= render 'form', client_app: @client_app %>
          <%= link_to 'Back', client_apps_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/client_apps/show.html.erb
<%= render 'client_apps/profile' do %>
  <div class="row">
    <div class="col m6 s12">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Recent Errors</span>
          <ul>
            <% @recent_errors.each do |error| %>
              <li><%= error %></li>
            <% end %>
          </ul>
        </div>
        <div class="card-action">
          <a href="#">View All</a>
        </div>
      </div>
    </div>
    <div class="col m6 s12">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Error Rate</span>
          <div class='text-center'>
          <h1>3%</h1>
          </div>
        </div>
        <div class="card-action">
          <a href="#">This is a link</a>
          <a href="#">This is a link</a>
        </div>
      </div>
    </div>
    <div class="col m6 s12">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Error Rate</span>
          <div class='text-center'>
          <h1>3%</h1>
          </div>
        </div>
        <div class="card-action">
          <a href="#">This is a link</a>
          <a href="#">This is a link</a>
        </div>
      </div>
    </div>
    <div class="col m6 s12">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
        </div>
        <div class="card-action">
          <a href="#">This is a link</a>
          <a href="#">This is a link</a>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/integrations/index.html.erb
<% breadcrumbs = [{text: 'Integrations', url: '#'}] %>
<%= render 'client_apps/profile', { breadcrumbs: breadcrumbs } do %>
  <div class='row'>
    <div class='col 12'>
      <h5>Your App</h5>
    </div>
  </div>
  <div class='row'>
    <div class='col 12'>
      <h5>Slack</h5>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Simpleerr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <a href="/" class="brand-logo">SimpleErr</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <% unless  user_signed_in? %>
            <li><%= link_to 'Log In', new_user_session_path %> </li>
          <% else %>
            <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete  %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class='container'>
      <div class='row'>
        <p class="notice"><%= notice %></p>
      </div>
      <div class='row'>
        <p class="alert"><%= alert %></p>
      </div>
    </div>
    <main>
      <%= yield %>
    </main>
    <footer class="page-footer">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">Footer Content</h5>
            <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Links</h5>
            <ul>
              <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
        © 2014 Copyright Text
        <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
        </div>
      </div>
    </footer>
  </body>
</html>